sonar.projectKey=usdot-fhwa-stol_ns3-federate
sonar.organization=usdot-fhwa-stol
sonar.projectName=ns3-federate
sonar.projectVersion=1.0
sonar.sources=src
sonar.coverage.exclusions=**/test/**
sonar.scm.provider=git
sonar.sourceEncoding=UTF-8